name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: jcacioppo
        password: ${{ secrets.JCACIOPPODOCKERHUBTOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: jcacioppo/dev-container
        flavor: |
          latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
